[package]
name = "minifb_wgpu_web_and_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Desktop dependencies.
minifb = "0.27.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Web dependencies.
minifb = { version = "0.27.0", default-features = false, features = ["web"] }
wasm-bindgen = "0.2.93"
console_error_panic_hook = "0.1.7"


[patch.crates-io]
# Need newer than 0.27.0 to fix a web compilation issue.
minifb = { git = "https://github.com/emoon/rust_minifb.git", commit = "bf377b4" }
